# Generated by Django 5.0 on 2023-12-13 16:05

import Chemistry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название растения')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('term', models.TextField(blank=True, verbose_name='Термин')),
                ('external_sign', models.TextField(blank=True, verbose_name='Внешний признак')),
                ('distribution', models.TextField(blank=True, verbose_name='Распространение')),
                ('chemical_composition', models.TextField(blank=True, verbose_name='Химический состав')),
                ('harvesting_drying', models.TextField(blank=True, verbose_name='Сбор, заготовка, сушка')),
                ('standardization', models.TextField(blank=True, verbose_name='Cтандартизация')),
                ('microscopy', models.TextField(blank=True, verbose_name='Микроскопия')),
                ('signs', models.TextField(blank=True, verbose_name='Внешние признаки сырья')),
                ('numerical_indicators', models.TextField(blank=True, verbose_name='Числовые показатели')),
                ('keeping', models.TextField(blank=True, verbose_name='Хранение')),
                ('usage', models.TextField(blank=True, verbose_name='Использование')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Вещество')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Вещество',
                'verbose_name_plural': 'Вещества',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Chemistry.models.get_image_filename, verbose_name='Изображение')),
                ('plant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Chemistry.plant', verbose_name='Название растения')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='category_plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Chemistry.substances', verbose_name='Категория вещества'),
        ),
    ]
